[package]
name = "server"
version = "0.0.0"
authors = ["Alex Fedoseev <alex@35mil.me>"]
license = "MIT"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
hyper = { version = "0.14.7", features = ["full"] }
